services:
  db:
    image: postgres:16-alpine
    container_name: db
    hostname: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=service-perfect-cv
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - fpt-network

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    command: redis-server --appendonly yes --requirepass redis123
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - fpt-network

networks:
  fpt-network:
    name: fpt-network

volumes:
  db-data:
  redis-data:
