services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU4-ubuntu-20.04
    container_name: db
    hostname: db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA:-Y}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:-SaStrongPassword!123}
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - fpt-network

networks:
  fpt-network:
    name: fpt-network

volumes:
  db-data:
