[build]
builder = "DOCKERFILE"
dockerfilePath = "src/service-cv-management/Dockerfile"
watchPatterns = ["src/service-cv-management/**"]

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
