[build]
builder = "DOCKERFILE"
dockerfilePath = "src/service-cv-management/Dockerfile"
buildContext   = "src/service-cv-management"

[deploy]
# With Dockerfile builder, Railway uses the image's ENTRYPOINT/CMD.
# You can remove startCommand, or leave it empty.
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
